sudo: false
language: android
jdk:
- openjdk8
env:
  global:
  - ANDROID=30
  - ANDROID_BUILD_TOOLS=30.0.2
  - GRADLE_OPTS="-Xmx2048m"
  - secure: UtoDY9kpdxNA7hwISdkz5lZTOGRuIxt+OF3K68jRLqG4MnGEO17jJ+cFMEDQ8iuPogNnlGNgsGrrqwTncCh9xftlDDcu29tzGCmoW74EwWni99ppgXbH3CQSFdZ7ubQ47ELbJPjnP6ITwmDURQ9C1beIJrRbHSe0H9Pg3kuIC5Me/aWEVTAoNuVjQD9cXI5GFcj1lO3QRRTMbS0Sy2zuoOwV4frWT3+NKzKZ69Y7B+w9QWnhAmYogeVk80UQZcHRgJD8jxz5B96uToZHun4uN4xIDLu011IffohuaZR2QHA9c1WmZNyN//gaflCYNphGYslupcft0AxhOYQvv9iQSgRgdPuocIPlHztbklEt1XgVxyU1XT9jw3zYIM4NsTSjBEs7txghZEQttxoroCXx/B8oqo6mof9Xjg1Tq/KShE8BWAAImxJNpGDEBKhcXwgGqls1YMD5+VW6ncGTuGWJVpFZVQ4sjD3+mWhCjgwBF5UP3U29e3WBROEdk80tqeTTt5yr28MbKDrG7SswnU0zFjvwrYNCunp7HZuFo7RzoYGyDujas6c+HE6uDMSYTFYRVRisX2U2fgYNGjShRiltTW7cj99BGm0+9edEj8+6snWqtxknEGk9sCSufv0OSdpddl7ZihaWyQ02VVDFXi1bKo9fNGwjx2wASZQr42NeZyE=
  - secure: U/PKpCUtnofYNfKJ4uS/OAir0Rq80QYirshnMg270XCHQDtZ82RAlLLPop2/9BtXhTH3tYvmBDjMhy4Z9o4dbGaUgVuVZ56u4E6O8KZUpVVCe8o2+ra0pTKoFWc62aQYAZjJtqZjrXQTeFFQULoHc4Ep5O95JWFLKK/74OqAQiAOr/3Y7hMWlA0l8ifM5U/3xsLqAYUBAw5d/GBg0gYtqZvt88cHrBwBk9caDPcjqTLdAX/CuH9Mkz5MK1obXPL6o2YDFNTVlVMXKlPJv/PCBGlAM8fRdTwFKJjQy2DZ9gio3xUGvaLo9PNQMLoLXIAPqUfd46VvuWXZXMW6Hv4bs6mc5yw6yYFLZdJGcE4tLe3SCFkt8yXyhvvRFVhG68aqzVY+JtKZ/UXhX9qhFaH5RsnjRA2Hw9R3Q1Azk81ZRRBtraDpzMsLV3MaFjoCdEEm/l3pcBYmXXlI/Mh02ZLgX+9a6nygAZvpCclrvLCPJyXQFqwP/d/jdZBwXWjj2TNGliXNkQBNr0XYY/wfHkjp8/cM7Y4NVAgX0Emrp7alnqZkcYvsGLkpjUV8NUwZQ63+cH5TSxtRefm6bwTF9BgxLfLekgH+XWA6Pp14KJsgX4OGAvExL6uryTaW9W0/yAa+f8hhPXnHN9YS8IyhPDIrJLwOcipqY8jOCvmYkU2QDCY=
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID
before_install:
- yes | sdkmanager "platforms;android-$ANDROID"
script:
- ./gradlew clean build
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  ./gradlew uploadArchives -PSONATYPE_USERNAME="${SONATYPE_USERNAME}" -PSONATYPE_PASSWORD="${SONATYPE_PASSWORD}";
  fi
notifications:
  email:
    recipients:
    - secure: TK+wKR6rBBIZWScbk8u2yNXiGAMPfDsb+CWowQgYwyowp9KXHmCrXKkNYRox4YQ0TJyvaCH9ys+qVmsPPOtA0Liyv5/4zFhM2+31lAqFUniqBGl4ozFNqN8f04vB5jkF8kA44L8Qt4tknaHaRE5k8Z9ENlTf9jNB2P/k6O9uMQzM5cLZF6KI0NUtVHZUMSPQ4BorpsuzWACyin7skLowVfD2m+K+ZK4LH3sYGFL1o1VwMnYSxS4TLZPQRQkUSwPJ7cjtgjlgorPGp84iHjuNA6VC4QzPNoUjjcci6efl8CMBBU5qzF+b0SRriG9bNGd4OPsje3Q4h23MGxxFN37B3uYr9ijylR0khHUdkQiF3U1x+vv6coEk5Ng3SFwXnDrJX9QaxyIQd8mWvhiCgYGnyisY401P1lrAPc4EINZviy6VCiLllH5M7liBX+5lZXxM8Dwon9ZRrtyUbjm3nx1pOuayZW8BWJXW+t316X+Yj0RUNEJMC9GpJKLFy1aeT2EkefTFQvJq82vfiwpqyII9x7te+Fqme0iHkJqg4WVF3VATsPwUyW3YxmbAQjYwAsh/+okeM0sySwSS4h0E7NM7HmQL05is4B5W9XzducWZPA+n8QczW8C7LDvtao8jUO2KVvPntHPjt1qmBR34Iy+pjoE317vHSIlbkgrjtSY8KGI=
    on_success: always
    on_failure: always
